<a href="https://colab.research.google.com/github/agrawalharish1997/Array-shorted-coloumn-wise-/blob/master/sortingarray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:

import numpy as np
arr2D = np.array([[11, 7, 13, 22], [11, 7, 23, 14], [31, 10, 33, 7]])
 
print('2D Numpy Array')
print(arr2D)
sortedArr = arr2D[arr2D[:,0].argsort()]
 
print('Sorted 2D Numpy Array')
print(sortedArr)


2D Numpy Array
[[11  7 13 22]
 [11  7 23 14]
 [31 10 33  7]]
Sorted 2D Numpy Array
[[11  7 13 22]
 [11  7 23 14]
 [31 10 33  7]]
